version: '3.8'

services:
  app-zeeven:
    container_name: app-zeeven
    # The official v2 Traefik docker image
    image: simachille/app-zeeven:latest
    restart: always
    ports:
      # The HTTP port
      - "82:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - API_URL=${API_URL}
      - API_URL=${API_URL}
      - APPLICATION_URL=${APPLICATION_URL}
      - BACKOFFICE_API=${BACKOFFICE_API}
      - BACKOFFICE_API_TOKEN=${BACKOFFICE_API_TOKEN}

      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}

      - JWT_SECRET=${JWT_SECRET}

      - NEXT_PUBLIC_API_KEY=${PUBLIC_API_KEY}
      - NEXT_PUBLIC_ASSETS_ENDPOINT=${PUBLIC_ASSETS_ENDPOINT}
      - NEXT_PUBLIC_CLIENT_ID=${PUBLIC_CLIENT_ID}
      - NEXT_PUBLIC_DISCOVERY_DOC=${PUBLIC_DISCOVERY_DOC}
      - NEXT_PUBLIC_GOOGLE_ANALYTICS=${PUBLIC_GOOGLE_ANALYTICS}
      - NEXT_PUBLIC_GOOGLE_MAP_API_KEY=${PUBLIC_GOOGLE_MAP_API_KEY}
      - NEXT_PUBLIC_SCOPES=${PUBLIC_SCOPES}
      - NEXT_PUBLIC_SECRET=${PUBLIC_SECRET}

      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - BACKOFFICE_API=${BACKOFFICE_API}
      - BACKOFFICE_API_TOKEN=${BACKOFFICE_API_TOKEN}

      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}

      - JWT_SECRET=${JWT_SECRET}

      - NEXT_PUBLIC_API_KEY=${PUBLIC_API_KEY}
      - NEXT_PUBLIC_ASSETS_ENDPOINT=${PUBLIC_ASSETS_ENDPOINT}
      - NEXT_PUBLIC_CLIENT_ID=${PUBLIC_CLIENT_ID}
      - NEXT_PUBLIC_DISCOVERY_DOC=${PUBLIC_DISCOVERY_DOC}
      - NEXT_PUBLIC_GOOGLE_ANALYTICS=${PUBLIC_GOOGLE_ANALYTICS}
      - NEXT_PUBLIC_GOOGLE_MAP_API_KEY=${PUBLIC_GOOGLE_MAP_API_KEY}
      - NEXT_PUBLIC_SCOPES=${PUBLIC_SCOPES}
      - NEXT_PUBLIC_SECRET=${PUBLIC_SECRET}

      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_URL_INTERNAL=${NEXTAUTH_URL_INTERNAL}

      - SERVICE_ID=${SERVICE_ID}
      - SERVICE_KEY=${SERVICE_KEY}











      - API_URL=http://ms-zeeven:8083
      - APPLICATION_URL=https://zeeven.fr
      - BACKOFFICE_API=http://192.168.1.101:8056

      - GOOGLE_ID=924982347085-bnvlr0fl0ductkogf29k6li2d2j21unn.apps.googleusercontent.com
      - GOOGLE_SECRET=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

      - JWT_SECRET=22238e57eea6a87d3f9aa125954465a8

      - NEXT_PUBLIC_API_KEY=AIzaSyATCg4041jPkG3jK9a4U6nqPdv6cGCi0tY
      - NEXT_PUBLIC_ASSETS_ENDPOINT=https://api.zeeven.fr
      - NEXT_PUBLIC_CLIENT_ID=621935878189-737vjf5m9e6ddfldut8fv47uhrlebh1t.apps.googleusercontent.com
      - NEXT_PUBLIC_DISCOVERY_DOC=https://www.googleapis.com/discovery/v1/apis/people/v1/rest
      - NEXT_PUBLIC_GOOGLE_ANALYTICS=G-NPL0MN9DYD
      - NEXT_PUBLIC_GOOGLE_MAP_API_KEY=AIzaSyC16NtMjeKoZm27_wu981AUL7PZi1BGzBM
      - NEXT_PUBLIC_SCOPES="https://www.googleapis.com/auth/contacts.readonly https://www.googleapis.com/auth/contacts.other.readonly"
      - NEXT_PUBLIC_SECRET=22238e57eea6a87d3f9aa125954465a8

      - NEXTAUTH_SECRET=LITk2nd7dnhZTpvdK2kK7KRhG0siromhRas8U3/9utg=
      - NEXTAUTH_URL=https://zeeven.fr
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000


      - SERVICE_ID=2a611283-e58d-41e1-904c-b04c3edb7be2
      - SERVICE_KEY=YWGEveUXq16Q5fv3QrUr9OxYS6376UScVEghcu9m59h2tYqECo2
    networks:
      - applications-network
networks:
  applications-network:
    external: true
    name: applications-network