version: '3.8'

services:
  app-zeeven:
    container_name: app-zeeven
    # The official v2 Traefik docker image
    image: simachille/app-zeeven:latest
    restart: always
    ports:
      # The HTTP port
      - "82:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NEXT_PUBLIC_GOOGLE_MAP_API_KEY=${NEXT_PUBLIC_GOOGLE_MAP_API_KEY}
      - APPLICATION_URL=${APPLICATION_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    networks:
      - applications-network
networks:
  applications-network:
    external: true
    name: applications-network